id: I8A7987A8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T21:01:54+00:00'
last_modified: '2022-06-08T00:53:38.785577+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6458
  title: ལག་ལེན་པོད་དམར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    910F:
      image_group_id: I3CN6460
      title: ''
      total_pages: 564
      order: 1
      base_file: 910F.txt
    00A8:
      image_group_id: I3CN6461
      title: ''
      total_pages: 660
      order: 2
      base_file: 00A8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
