id: P004420
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:20:00.386744
source_metadata:
  id: bdr:W3CN6458
  title: ལག་ལེན་པོད་དམར།
  author: ''
  volumes:
    bc07d0d8acdb4a11a3da46dbeb925c30:
      image_group_id: I3CN6460
      title: ''
      volume_number: 1
      total_pages: 564
      base_file: v001.txt
    ffe77f88e86b40f0b3645bdc502cf513:
      image_group_id: I3CN6461
      title: ''
      volume_number: 2
      total_pages: 660
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
